#ifndef random_pipeline_SCHEDULE_H
#define random_pipeline_SCHEDULE_H

// MACHINE GENERATED -- DO NOT EDIT
// This schedule was automatically generated by Adams2019
// for target=x86-64-linux-avx-avx2-avx512-avx512_cannonlake-avx512_sapphirerapids-avx512_skylake-f16c-fma-sse41  // NOLINT
// with autoscheduler_params=autoscheduler=Adams2019

#include "Halide.h"


inline void apply_schedule_random_pipeline(
    ::Halide::Pipeline pipeline,
    ::Halide::Target target
) {
    using ::Halide::Func;
    using ::Halide::MemoryType;
    using ::Halide::RVar;
    using ::Halide::TailStrategy;
    using ::Halide::Var;
    Func casted = pipeline.get_func(14);
    Func upsampled_nn__0_1 = pipeline.get_func(13);
    Func all_r_4 = pipeline.get_func(12);
    Func constant_exterior_2 = pipeline.get_func(11);
    Func repeat_edge_9 = pipeline.get_func(10);
    Func downsampled_nn__0_1 = pipeline.get_func(9);
    Func binary_op_1 = pipeline.get_func(8);
    Func binary_op = pipeline.get_func(7);
    Func constant_exterior = pipeline.get_func(6);
    Func repeat_edge_7 = pipeline.get_func(5);
    Func all = pipeline.get_func(4);
    Func downsampled_nn__0 = pipeline.get_func(3);
    Func repeat_edge = pipeline.get_func(2);
    Func lambda_0 = pipeline.get_func(1);
    Var _0(casted.get_schedule().dims()[0].var);
    Var _0i("_0i");
    Var _1(casted.get_schedule().dims()[1].var);
    Var _1i("_1i");
    Var _2(casted.get_schedule().dims()[2].var);
    Var _2i("_2i");
    RVar r241_x(all_r_4.update(0).get_schedule().dims()[0].var);
    casted
        .split(_1, _1, _1i, 8, TailStrategy::ShiftInwards)
        .split(_0, _0, _0i, 16, TailStrategy::ShiftInwards)
        .vectorize(_0i)
        .compute_root()
        .reorder({_0i, _0, _1i, _2, _1})
        .parallel(_1);
    all_r_4
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    all_r_4.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r241_x, _0, _1, _2});
    constant_exterior_2
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    downsampled_nn__0_1
        .split(_2, _2, _2i, 16, TailStrategy::RoundUp)
        .vectorize(_2i)
        .compute_at(casted, _1)
        .reorder({_2i, _2, _0, _1})
        .reorder_storage(_2, _0, _1);
    downsampled_nn__0
        .split(_0, _0, _0i, 16, TailStrategy::ShiftInwards)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});

}

#endif  // random_pipeline_SCHEDULE_H
