#ifndef random_pipeline_SCHEDULE_H
#define random_pipeline_SCHEDULE_H

// MACHINE GENERATED -- DO NOT EDIT
// This schedule was automatically generated by Adams2019
// for target=x86-64-linux-avx-avx2-avx512-avx512_cannonlake-avx512_sapphirerapids-avx512_skylake-f16c-fma-sse41  // NOLINT
// with autoscheduler_params=autoscheduler=Adams2019

#include "Halide.h"


inline void apply_schedule_random_pipeline(
    ::Halide::Pipeline pipeline,
    ::Halide::Target target
) {
    using ::Halide::Func;
    using ::Halide::MemoryType;
    using ::Halide::RVar;
    using ::Halide::TailStrategy;
    using ::Halide::Var;
    Func casted = pipeline.get_func(24);
    Func all_r_8 = pipeline.get_func(23);
    Func conv_w__0 = pipeline.get_func(22);
    Func sum_2 = pipeline.get_func(21);
    Func all_r_7 = pipeline.get_func(20);
    Func constant_exterior_1 = pipeline.get_func(19);
    Func repeat_edge_7 = pipeline.get_func(18);
    Func binary_op_2 = pipeline.get_func(17);
    Func binary_op = pipeline.get_func(16);
    Func all_r_3 = pipeline.get_func(15);
    Func conv2D__0_1 = pipeline.get_func(14);
    Func all_r_5 = pipeline.get_func(13);
    Func binary_op_1 = pipeline.get_func(12);
    Func all_r_4 = pipeline.get_func(11);
    Func all_r_2 = pipeline.get_func(10);
    Func constant_exterior = pipeline.get_func(9);
    Func repeat_edge_6 = pipeline.get_func(8);
    Func all_r_1 = pipeline.get_func(7);
    Func sliced = pipeline.get_func(6);
    Func upsampled_linear__0 = pipeline.get_func(5);
    Func all_r = pipeline.get_func(4);
    Func downsampled_nn__0 = pipeline.get_func(3);
    Func repeat_image = pipeline.get_func(2);
    Func lambda_0 = pipeline.get_func(1);
    Var _0(casted.get_schedule().dims()[0].var);
    Var _0i("_0i");
    Var _1(casted.get_schedule().dims()[1].var);
    Var _1i("_1i");
    Var _2(casted.get_schedule().dims()[2].var);
    Var _2i("_2i");
    Var r111_x(all_r_1.update(0).get_schedule().dims()[0].var);
    Var r175_x(all_r_4.update(0).get_schedule().dims()[0].var);
    RVar r128_x(all_r_2.update(0).get_schedule().dims()[0].var);
    RVar r139_x(all_r_3.update(0).get_schedule().dims()[0].var);
    RVar r189_x(all_r_5.update(0).get_schedule().dims()[0].var);
    RVar r248_x(all_r_7.update(0).get_schedule().dims()[0].var);
    RVar r259_x(sum_2.update(0).get_schedule().dims()[0].var);
    RVar r281_x(all_r_8.update(0).get_schedule().dims()[0].var);
    RVar r88_x(all_r.update(0).get_schedule().dims()[0].var);
    casted
        .split(_1, _1, _1i, 8, TailStrategy::ShiftInwards)
        .split(_0, _0, _0i, 16, TailStrategy::ShiftInwards)
        .vectorize(_0i)
        .compute_root()
        .reorder({_0i, _0, _1i, _2, _1})
        .parallel(_1);
    all_r_8
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    all_r_8.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r281_x, _0, _1, _2});
    sum_2
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    sum_2.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r259_x, _0, _1, _2});
    all_r_7
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    all_r_7.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r248_x, _0, _1, _2});
    constant_exterior_1
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    binary_op
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    all_r_3
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    all_r_3.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r139_x, _0, _1, _2});
    conv2D__0_1
        .split(_1, _1, _1i, 500, TailStrategy::RoundUp)
        .split(_2, _2, _2i, 5, TailStrategy::RoundUp)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_root()
        .reorder({_0i, _0, _1i, _2i, _1, _2})
        .fuse(_1, _2, _1)
        .parallel(_1);
    all_r_5
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    all_r_5.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r189_x, _0, _1, _2});
    binary_op_1
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    all_r_4
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    all_r_4.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, _0, r175_x, _1, _2});
    all_r_2
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    all_r_2.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r128_x, _0, _1, _2});
    constant_exterior
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    all_r_1
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    all_r_1.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, _0, r111_x, _1, _2});
    sliced
        .split(_1, _1, _1i, 8, TailStrategy::ShiftInwards)
        .split(_0, _0, _0i, 16, TailStrategy::ShiftInwards)
        .vectorize(_0i)
        .compute_root()
        .reorder({_0i, _0, _1i, _1, _2})
        .parallel(_1);
    all_r
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(sliced, _1)
        .reorder({_0i, _0, _1, _2});
    all_r.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r88_x, _0, _1, _2});
    lambda_0
        .split(_0, _0, _0i, 16, TailStrategy::ShiftInwards)
        .vectorize(_0i)
        .compute_at(sliced, _1)
        .reorder({_0i, _0, _1, _2});

}

#endif  // random_pipeline_SCHEDULE_H
