#ifndef random_pipeline_SCHEDULE_H
#define random_pipeline_SCHEDULE_H

// MACHINE GENERATED -- DO NOT EDIT
// This schedule was automatically generated by Adams2019
// for target=x86-64-linux-avx-avx2-avx512-avx512_cannonlake-avx512_sapphirerapids-avx512_skylake-f16c-fma-sse41  // NOLINT
// with autoscheduler_params=autoscheduler=Adams2019

#include "Halide.h"


inline void apply_schedule_random_pipeline(
    ::Halide::Pipeline pipeline,
    ::Halide::Target target
) {
    using ::Halide::Func;
    using ::Halide::MemoryType;
    using ::Halide::RVar;
    using ::Halide::TailStrategy;
    using ::Halide::Var;
    Func casted = pipeline.get_func(9);
    Func all_r_9 = pipeline.get_func(8);
    Func constant_exterior = pipeline.get_func(7);
    Func repeat_edge_7 = pipeline.get_func(6);
    Func relu = pipeline.get_func(5);
    Func sliced = pipeline.get_func(4);
    Func all_r = pipeline.get_func(3);
    Func repeat_edge = pipeline.get_func(2);
    Func lambda_0 = pipeline.get_func(1);
    Var _0(casted.get_schedule().dims()[0].var);
    Var _0i("_0i");
    Var _1(casted.get_schedule().dims()[1].var);
    Var _1i("_1i");
    Var _2(casted.get_schedule().dims()[2].var);
    Var r295_x(all_r_9.update(0).get_schedule().dims()[0].var);
    RVar r85_x(all_r.update(0).get_schedule().dims()[0].var);
    casted
        .split(_1, _1, _1i, 8, TailStrategy::ShiftInwards)
        .split(_0, _0, _0i, 16, TailStrategy::ShiftInwards)
        .vectorize(_0i)
        .compute_root()
        .reorder({_0i, _0, _1i, _2, _1})
        .parallel(_1);
    all_r_9
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    all_r_9.update(0)
        .split(_0, _0, _0i, 32, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, _0, r295_x, _1, _2});
    constant_exterior
        .split(_0, _0, _0i, 32, TailStrategy::ShiftInwards)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    all_r
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    all_r.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::GuardWithIf)
        .vectorize(_0i)
        .reorder({_0i, r85_x, _0, _1, _2});

}

#endif  // random_pipeline_SCHEDULE_H
