#ifndef random_pipeline_SCHEDULE_H
#define random_pipeline_SCHEDULE_H

// MACHINE GENERATED -- DO NOT EDIT
// This schedule was automatically generated by Adams2019
// for target=x86-64-linux-avx-avx2-avx512-avx512_cannonlake-avx512_sapphirerapids-avx512_skylake-f16c-fma-sse41  // NOLINT
// with autoscheduler_params=autoscheduler=Adams2019

#include "Halide.h"


inline void apply_schedule_random_pipeline(
    ::Halide::Pipeline pipeline,
    ::Halide::Target target
) {
    using ::Halide::Func;
    using ::Halide::MemoryType;
    using ::Halide::RVar;
    using ::Halide::TailStrategy;
    using ::Halide::Var;
    Func casted = pipeline.get_func(14);
    Func all_r_4 = pipeline.get_func(13);
    Func conv_w__0_1 = pipeline.get_func(12);
    Func sum_6 = pipeline.get_func(11);
    Func all_1 = pipeline.get_func(10);
    Func pool2D_r__0_1_1 = pipeline.get_func(9);
    Func conv_w__1 = pipeline.get_func(8);
    Func sum_4 = pipeline.get_func(7);
    Func all_w = pipeline.get_func(6);
    Func sum = pipeline.get_func(5);
    Func pool2D_r__0_1 = pipeline.get_func(4);
    Func all = pipeline.get_func(3);
    Func mirror_interior = pipeline.get_func(2);
    Func lambda_0 = pipeline.get_func(1);
    Var _0(casted.get_schedule().dims()[0].var);
    Var _0i("_0i");
    Var _0ii("_0ii");
    Var _1(casted.get_schedule().dims()[1].var);
    Var _1i("_1i");
    Var _2(casted.get_schedule().dims()[2].var);
    RVar r113_x(sum.update(0).get_schedule().dims()[0].var);
    RVar r201_x(sum_4.update(0).get_schedule().dims()[0].var);
    RVar r223_x(pool2D_r__0_1_1.update(0).get_schedule().dims()[0].var);
    RVar r223_y(pool2D_r__0_1_1.update(0).get_schedule().dims()[1].var);
    RVar r301_x(sum_6.update(0).get_schedule().dims()[0].var);
    RVar r323_x(all_r_4.update(0).get_schedule().dims()[0].var);
    RVar r88_x(pool2D_r__0_1.update(0).get_schedule().dims()[0].var);
    RVar r88_y(pool2D_r__0_1.update(0).get_schedule().dims()[1].var);
    casted
        .split(_0, _0, _0i, 256, TailStrategy::ShiftInwards)
        .split(_1, _1, _1i, 63, TailStrategy::ShiftInwards)
        .split(_0i, _0i, _0ii, 16, TailStrategy::ShiftInwards)
        .vectorize(_0ii)
        .compute_root()
        .reorder({_0ii, _0i, _1i, _2, _0, _1})
        .fuse(_0, _1, _0)
        .parallel(_0);
    all_r_4
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _0)
        .reorder({_0i, _0, _1, _2});
    all_r_4.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r323_x, _0, _1, _2});
    sum_6
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _0)
        .reorder({_0i, _0, _1, _2});
    sum_6.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r301_x, _0, _1, _2});
    all_1
        .split(_0, _0, _0i, 32, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _0)
        .reorder({_0i, _0, _1, _2});
    pool2D_r__0_1_1
        .split(_0, _0, _0i, 32, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _0)
        .reorder({_0i, _0, _1, _2});
    pool2D_r__0_1_1.update(0)
        .split(_0, _0, _0i, 32, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r223_x, r223_y, _0, _1, _2});
    sum_4
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _0)
        .reorder({_0i, _0, _1, _2});
    sum_4.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r201_x, _0, _1, _2});
    sum
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _0)
        .reorder({_0i, _0, _1, _2});
    sum.update(0)
        .split(_0, _0, _0i, 32, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r113_x, _0, _1, _2});
    pool2D_r__0_1
        .split(_0, _0, _0i, 32, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _0)
        .reorder({_0i, _0, _1, _2});
    pool2D_r__0_1.update(0)
        .split(_0, _0, _0i, 32, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r88_x, r88_y, _0, _1, _2});
    all
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _0)
        .reorder({_0i, _0, _1, _2});
    mirror_interior
        .split(_0, _0, _0i, 16, TailStrategy::ShiftInwards)
        .vectorize(_0i)
        .compute_at(casted, _0)
        .reorder({_0i, _0, _1, _2});

}

#endif  // random_pipeline_SCHEDULE_H
