#ifndef random_pipeline_SCHEDULE_H
#define random_pipeline_SCHEDULE_H

// MACHINE GENERATED -- DO NOT EDIT
// This schedule was automatically generated by Adams2019
// for target=x86-64-linux-avx-avx2-avx512-avx512_cannonlake-avx512_sapphirerapids-avx512_skylake-f16c-fma-sse41  // NOLINT
// with autoscheduler_params=autoscheduler=Adams2019

#include "Halide.h"


inline void apply_schedule_random_pipeline(
    ::Halide::Pipeline pipeline,
    ::Halide::Target target
) {
    using ::Halide::Func;
    using ::Halide::MemoryType;
    using ::Halide::RVar;
    using ::Halide::TailStrategy;
    using ::Halide::Var;
    Func casted = pipeline.get_func(12);
    Func upsampled_linear__1_2 = pipeline.get_func(11);
    Func upsampled_linear__0 = pipeline.get_func(10);
    Func all_r_3 = pipeline.get_func(9);
    Func downsampled_box__0 = pipeline.get_func(8);
    Func pool2D_r__0_1 = pipeline.get_func(7);
    Func binary_op_1 = pipeline.get_func(6);
    Func all_r_2 = pipeline.get_func(5);
    Func all = pipeline.get_func(4);
    Func relu = pipeline.get_func(3);
    Func mirror_interior = pipeline.get_func(2);
    Func lambda_0 = pipeline.get_func(1);
    Var _0(casted.get_schedule().dims()[0].var);
    Var _0i("_0i");
    Var _1(casted.get_schedule().dims()[1].var);
    Var _1i("_1i");
    Var _2(casted.get_schedule().dims()[2].var);
    RVar r193_x(all_r_2.update(0).get_schedule().dims()[0].var);
    RVar r216_x(pool2D_r__0_1.update(0).get_schedule().dims()[0].var);
    RVar r216_y(pool2D_r__0_1.update(0).get_schedule().dims()[1].var);
    RVar r233_x(all_r_3.update(0).get_schedule().dims()[0].var);
    casted
        .split(_1, _1, _1i, 63, TailStrategy::ShiftInwards)
        .split(_0, _0, _0i, 16, TailStrategy::ShiftInwards)
        .vectorize(_0i)
        .compute_root()
        .reorder({_0i, _0, _1i, _1, _2})
        .fuse(_1, _2, _1)
        .parallel(_1);
    upsampled_linear__0
        .split(_0, _0, _0i, 32, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    all_r_3
        .split(_1, _1, _1i, 4, TailStrategy::RoundUp)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_root()
        .reorder({_0i, _0, _1i, _2, _1})
        .parallel(_1);
    all_r_3.update(0)
        .split(_1, _1, _1i, 4, TailStrategy::GuardWithIf)
        .split(_0, _0, _0i, 32, TailStrategy::GuardWithIf)
        .vectorize(_0i)
        .reorder({_0i, r233_x, _0, _1i, _2, _1})
        .parallel(_1);
    downsampled_box__0
        .split(_0, _0, _0i, 32, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(all_r_3, _1)
        .reorder({_0i, _0, _1, _2});
    pool2D_r__0_1
        .split(_0, _0, _0i, 32, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(all_r_3, _1)
        .reorder({_0i, _0, _1, _2});
    pool2D_r__0_1.update(0)
        .split(_0, _0, _0i, 32, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r216_x, r216_y, _0, _1, _2});
    binary_op_1
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(all_r_3, _1)
        .reorder({_0i, _0, _1, _2});
    all_r_2
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(all_r_3, _1)
        .reorder({_0i, _0, _1, _2});
    all_r_2.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r193_x, _0, _1, _2});
    mirror_interior
        .split(_0, _0, _0i, 16, TailStrategy::ShiftInwards)
        .vectorize(_0i)
        .compute_at(all_r_3, _1)
        .reorder({_0i, _0, _1, _2});

}

#endif  // random_pipeline_SCHEDULE_H
