#ifndef random_pipeline_SCHEDULE_H
#define random_pipeline_SCHEDULE_H

// MACHINE GENERATED -- DO NOT EDIT
// This schedule was automatically generated by Adams2019
// for target=x86-64-linux-avx-avx2-avx512-avx512_cannonlake-avx512_sapphirerapids-avx512_skylake-f16c-fma-sse41  // NOLINT
// with autoscheduler_params=autoscheduler=Adams2019

#include "Halide.h"


inline void apply_schedule_random_pipeline(
    ::Halide::Pipeline pipeline,
    ::Halide::Target target
) {
    using ::Halide::Func;
    using ::Halide::MemoryType;
    using ::Halide::RVar;
    using ::Halide::TailStrategy;
    using ::Halide::Var;
    Func casted = pipeline.get_func(11);
    Func upsampled_nn__1 = pipeline.get_func(10);
    Func downsampled_box__0 = pipeline.get_func(9);
    Func pool2D_r__0_1 = pipeline.get_func(8);
    Func binary_op_1 = pipeline.get_func(7);
    Func upsampled_nn__0_1 = pipeline.get_func(6);
    Func relu = pipeline.get_func(5);
    Func upsampled_linear__0 = pipeline.get_func(4);
    Func downsampled_nn__1 = pipeline.get_func(3);
    Func repeat_edge = pipeline.get_func(2);
    Func lambda_0 = pipeline.get_func(1);
    Var _0(casted.get_schedule().dims()[0].var);
    Var _0i("_0i");
    Var _0ii("_0ii");
    Var _1(casted.get_schedule().dims()[1].var);
    Var _1i("_1i");
    Var _2(casted.get_schedule().dims()[2].var);
    RVar r118_x(pool2D_r__0_1.update(0).get_schedule().dims()[0].var);
    RVar r118_y(pool2D_r__0_1.update(0).get_schedule().dims()[1].var);
    casted
        .split(_0, _0, _0i, 1024, TailStrategy::ShiftInwards)
        .split(_1, _1, _1i, 63, TailStrategy::ShiftInwards)
        .split(_0i, _0i, _0ii, 32, TailStrategy::ShiftInwards)
        .vectorize(_0ii)
        .compute_root()
        .reorder({_0ii, _0i, _1i, _0, _1, _2})
        .fuse(_1, _2, _1)
        .fuse(_0, _1, _0)
        .parallel(_0);
    upsampled_nn__1
        .split(_0, _0, _0i, 32, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _0)
        .reorder({_0i, _0, _1, _2});
    downsampled_box__0
        .split(_0, _0, _0i, 32, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _0)
        .reorder({_0i, _0, _1, _2});
    pool2D_r__0_1
        .split(_0, _0, _0i, 32, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _0)
        .reorder({_0i, _0, _1, _2});
    pool2D_r__0_1.update(0)
        .split(_0, _0, _0i, 32, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r118_x, r118_y, _0, _1, _2});
    binary_op_1
        .split(_0, _0, _0i, 64, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _0)
        .reorder({_0i, _0, _1, _2});
    relu
        .split(_0, _0, _0i, 64, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _0)
        .reorder({_0i, _0, _1, _2});
    downsampled_nn__1
        .split(_0, _0, _0i, 16, TailStrategy::ShiftInwards)
        .vectorize(_0i)
        .compute_at(casted, _0)
        .reorder({_0i, _0, _1, _2});

}

#endif  // random_pipeline_SCHEDULE_H
