#ifndef random_pipeline_SCHEDULE_H
#define random_pipeline_SCHEDULE_H

// MACHINE GENERATED -- DO NOT EDIT
// This schedule was automatically generated by Adams2019
// for target=x86-64-linux-avx-avx2-avx512-avx512_cannonlake-avx512_sapphirerapids-avx512_skylake-f16c-fma-sse41  // NOLINT
// with autoscheduler_params=autoscheduler=Adams2019

#include "Halide.h"


inline void apply_schedule_random_pipeline(
    ::Halide::Pipeline pipeline,
    ::Halide::Target target
) {
    using ::Halide::Func;
    using ::Halide::MemoryType;
    using ::Halide::RVar;
    using ::Halide::TailStrategy;
    using ::Halide::Var;
    Func casted = pipeline.get_func(20);
    Func all_r_4 = pipeline.get_func(19);
    Func downsampled_box__1 = pipeline.get_func(18);
    Func all = pipeline.get_func(17);
    Func constant_exterior_2 = pipeline.get_func(16);
    Func repeat_edge_8 = pipeline.get_func(15);
    Func binary_op_4 = pipeline.get_func(14);
    Func all_r_2 = pipeline.get_func(13);
    Func conv2D_w__0_1 = pipeline.get_func(12);
    Func sum_1 = pipeline.get_func(11);
    Func upsampled_nn__1_1 = pipeline.get_func(10);
    Func conv_w__1 = pipeline.get_func(9);
    Func sum = pipeline.get_func(8);
    Func upsampled_nn__1 = pipeline.get_func(7);
    Func constant_exterior = pipeline.get_func(6);
    Func repeat_edge = pipeline.get_func(5);
    Func lambda_0 = pipeline.get_func(4);
    Func repeat_edge_6 = pipeline.get_func(2);
    Func lambda_6 = pipeline.get_func(1);
    Var _0(casted.get_schedule().dims()[0].var);
    Var _0i("_0i");
    Var _1(casted.get_schedule().dims()[1].var);
    Var _1i("_1i");
    Var _2(casted.get_schedule().dims()[2].var);
    Var _3(repeat_edge_6.get_schedule().dims()[3].var);
    Var r231_x(all_r_2.update(0).get_schedule().dims()[0].var);
    Var r299_x(all_r_4.update(0).get_schedule().dims()[0].var);
    RVar r131_x(sum_1.update(0).get_schedule().dims()[0].var);
    RVar r131_y(sum_1.update(0).get_schedule().dims()[1].var);
    RVar r131_z(sum_1.update(0).get_schedule().dims()[2].var);
    RVar r91_x(sum.update(0).get_schedule().dims()[0].var);
    casted
        .split(_1, _1, _1i, 8, TailStrategy::ShiftInwards)
        .split(_0, _0, _0i, 16, TailStrategy::ShiftInwards)
        .vectorize(_0i)
        .compute_root()
        .reorder({_0i, _0, _1i, _2, _1})
        .parallel(_1);
    all_r_4
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    all_r_4.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, _0, r299_x, _1, _2});
    downsampled_box__1
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    all_r_2
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    all_r_2.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, _0, r231_x, _1, _2});
    sum_1
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _2, _1})
        .reorder_storage(_0, _2, _1);
    sum_1.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r131_x, r131_y, r131_z, _0, _2, _1});
    upsampled_nn__1_1
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    conv_w__1
        .split(_1, _1, _1i, 126, TailStrategy::ShiftInwards)
        .split(_0, _0, _0i, 16, TailStrategy::ShiftInwards)
        .vectorize(_0i)
        .compute_root()
        .reorder({_0i, _0, _1i, _1, _2})
        .fuse(_1, _2, _1)
        .parallel(_1);
    sum
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(conv_w__1, _1)
        .reorder({_0i, _0, _1, _2});
    sum.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r91_x, _0, _1, _2});
    upsampled_nn__1
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(conv_w__1, _1)
        .reorder({_0i, _0, _1, _2});
    constant_exterior
        .split(_0, _0, _0i, 16, TailStrategy::ShiftInwards)
        .vectorize(_0i)
        .compute_at(conv_w__1, _1)
        .reorder({_0i, _0, _1, _2});
    repeat_edge_6
        .split(_1, _1, _1i, 16, TailStrategy::GuardWithIf)
        .vectorize(_1i)
        .compute_root()
        .reorder({_1i, _1, _0, _2, _3})
        .fuse(_0, _2, _0)
        .parallel(_0)
        .reorder_storage(_1, _0, _2, _3);

}

#endif  // random_pipeline_SCHEDULE_H
