#ifndef random_pipeline_SCHEDULE_H
#define random_pipeline_SCHEDULE_H

// MACHINE GENERATED -- DO NOT EDIT
// This schedule was automatically generated by Adams2019
// for target=x86-64-linux-avx-avx2-avx512-avx512_cannonlake-avx512_sapphirerapids-avx512_skylake-f16c-fma-sse41  // NOLINT
// with autoscheduler_params=autoscheduler=Adams2019

#include "Halide.h"


inline void apply_schedule_random_pipeline(
    ::Halide::Pipeline pipeline,
    ::Halide::Target target
) {
    using ::Halide::Func;
    using ::Halide::MemoryType;
    using ::Halide::RVar;
    using ::Halide::TailStrategy;
    using ::Halide::Var;
    Func casted = pipeline.get_func(16);
    Func all_r_5 = pipeline.get_func(15);
    Func conv_w__0 = pipeline.get_func(14);
    Func sum_2 = pipeline.get_func(13);
    Func all_r_4 = pipeline.get_func(12);
    Func conv2D_r__0_1_2 = pipeline.get_func(11);
    Func repeat_edge_5 = pipeline.get_func(10);
    Func lambda_6 = pipeline.get_func(9);
    Func all_r_2 = pipeline.get_func(7);
    Func relu = pipeline.get_func(6);
    Func constant_exterior = pipeline.get_func(5);
    Func repeat_edge_6 = pipeline.get_func(4);
    Func all_r = pipeline.get_func(3);
    Func mirror_interior = pipeline.get_func(2);
    Func lambda_0 = pipeline.get_func(1);
    Var _0(casted.get_schedule().dims()[0].var);
    Var _0i("_0i");
    Var _0ii("_0ii");
    Var _1(casted.get_schedule().dims()[1].var);
    Var _1i("_1i");
    Var _2(casted.get_schedule().dims()[2].var);
    Var _2i("_2i");
    Var _3(repeat_edge_5.get_schedule().dims()[3].var);
    RVar r158_x(all_r_2.update(0).get_schedule().dims()[0].var);
    RVar r191_x(conv2D_r__0_1_2.update(0).get_schedule().dims()[0].var);
    RVar r191_y(conv2D_r__0_1_2.update(0).get_schedule().dims()[1].var);
    RVar r191_z(conv2D_r__0_1_2.update(0).get_schedule().dims()[2].var);
    RVar r219_x(all_r_4.update(0).get_schedule().dims()[0].var);
    RVar r255_x(sum_2.update(0).get_schedule().dims()[0].var);
    RVar r277_x(all_r_5.update(0).get_schedule().dims()[0].var);
    RVar r85_x(all_r.update(0).get_schedule().dims()[0].var);
    casted
        .split(_0, _0, _0i, 1008, TailStrategy::ShiftInwards)
        .split(_1, _1, _1i, 16, TailStrategy::ShiftInwards)
        .split(_0i, _0i, _0ii, 16, TailStrategy::ShiftInwards)
        .vectorize(_0ii)
        .compute_root()
        .reorder({_0ii, _0i, _1i, _2, _0, _1})
        .fuse(_0, _1, _0)
        .parallel(_0);
    all_r_5
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _0)
        .reorder({_0i, _0, _1, _2});
    all_r_5.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r277_x, _0, _1, _2});
    sum_2
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _0)
        .reorder({_0i, _0, _1, _2});
    sum_2.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r255_x, _0, _1, _2});
    all_r_4
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _0)
        .reorder({_0i, _0, _1, _2});
    all_r_4.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r219_x, _0, _1, _2});
    conv2D_r__0_1_2
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _0)
        .reorder({_0i, _0, _1, _2});
    conv2D_r__0_1_2.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r191_x, r191_y, r191_z, _0, _1, _2});
    repeat_edge_5
        .split(_0, _0, _0i, 16, TailStrategy::ShiftInwards)
        .split(_1, _1, _1i, 4, TailStrategy::ShiftInwards)
        .split(_2, _2, _2i, 2, TailStrategy::ShiftInwards)
        .vectorize(_0i)
        .compute_root()
        .reorder({_0i, _1i, _2i, _3, _0, _1, _2})
        .fuse(_1, _2, _1)
        .fuse(_0, _1, _0)
        .parallel(_0);
    all_r_2
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _0)
        .reorder({_0i, _0, _1, _2});
    all_r_2.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r158_x, _0, _1, _2});
    relu
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _0)
        .reorder({_0i, _0, _1, _2});
    all_r
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _0)
        .reorder({_0i, _0, _1, _2});
    all_r.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r85_x, _0, _1, _2});
    mirror_interior
        .split(_0, _0, _0i, 16, TailStrategy::ShiftInwards)
        .vectorize(_0i)
        .compute_at(casted, _0)
        .reorder({_0i, _0, _1, _2});

}

#endif  // random_pipeline_SCHEDULE_H
