#ifndef random_pipeline_SCHEDULE_H
#define random_pipeline_SCHEDULE_H

// MACHINE GENERATED -- DO NOT EDIT
// This schedule was automatically generated by Adams2019
// for target=x86-64-linux-avx-avx2-avx512-avx512_cannonlake-avx512_sapphirerapids-avx512_skylake-f16c-fma-sse41  // NOLINT
// with autoscheduler_params=autoscheduler=Adams2019

#include "Halide.h"


inline void apply_schedule_random_pipeline(
    ::Halide::Pipeline pipeline,
    ::Halide::Target target
) {
    using ::Halide::Func;
    using ::Halide::MemoryType;
    using ::Halide::RVar;
    using ::Halide::TailStrategy;
    using ::Halide::Var;
    Func casted = pipeline.get_func(19);
    Func all_r_4 = pipeline.get_func(18);
    Func constant_exterior_1 = pipeline.get_func(17);
    Func repeat_edge_7 = pipeline.get_func(16);
    Func relu_1 = pipeline.get_func(15);
    Func conv2D_r__0_1 = pipeline.get_func(14);
    Func repeat_edge_2 = pipeline.get_func(13);
    Func lambda_3 = pipeline.get_func(12);
    Func binary_op = pipeline.get_func(10);
    Func all_w = pipeline.get_func(9);
    Func sum_1 = pipeline.get_func(8);
    Func all_r_1 = pipeline.get_func(7);
    Func conv_w__1 = pipeline.get_func(6);
    Func sum = pipeline.get_func(5);
    Func sliced = pipeline.get_func(4);
    Func all_r = pipeline.get_func(3);
    Func mirror_image = pipeline.get_func(2);
    Func lambda_0 = pipeline.get_func(1);
    Var _0(casted.get_schedule().dims()[0].var);
    Var _0i("_0i");
    Var _1(casted.get_schedule().dims()[1].var);
    Var _1i("_1i");
    Var _2(casted.get_schedule().dims()[2].var);
    Var _3(repeat_edge_2.get_schedule().dims()[3].var);
    Var _3i("_3i");
    Var r121_x(sum_1.update(0).get_schedule().dims()[0].var);
    Var r143_x(all_r_1.update(0).get_schedule().dims()[0].var);
    RVar r157_x(conv2D_r__0_1.update(0).get_schedule().dims()[0].var);
    RVar r157_y(conv2D_r__0_1.update(0).get_schedule().dims()[1].var);
    RVar r157_z(conv2D_r__0_1.update(0).get_schedule().dims()[2].var);
    RVar r238_x(all_r_4.update(0).get_schedule().dims()[0].var);
    RVar r85_x(all_r.update(0).get_schedule().dims()[0].var);
    RVar r99_x(sum.update(0).get_schedule().dims()[0].var);
    casted
        .split(_1, _1, _1i, 8, TailStrategy::ShiftInwards)
        .split(_0, _0, _0i, 16, TailStrategy::ShiftInwards)
        .vectorize(_0i)
        .compute_root()
        .reorder({_0i, _0, _1i, _2, _1})
        .parallel(_1);
    all_r_4
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    all_r_4.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r238_x, _0, _1, _2});
    conv2D_r__0_1
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    conv2D_r__0_1.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, r157_x, r157_y, r157_z, _0, _1, _2});
    repeat_edge_2
        .split(_3, _3, _3i, 16, TailStrategy::ShiftInwards)
        .split(_0, _0, _0i, 2, TailStrategy::ShiftInwards)
        .vectorize(_3i)
        .compute_root()
        .reorder({_3i, _0i, _1, _2, _3, _0})
        .fuse(_3, _0, _3)
        .parallel(_3)
        .reorder_storage(_3, _0, _1, _2);
    binary_op
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    sum_1
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    sum_1.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, _0, r121_x, _1, _2});
    all_r_1
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(casted, _1)
        .reorder({_0i, _0, _1, _2});
    all_r_1.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .reorder({_0i, _0, r143_x, _1, _2});
    sum
        .split(_1, _1, _1i, 32, TailStrategy::RoundUp)
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_root()
        .reorder({_0i, _0, _1i, _1, _2})
        .parallel(_1);
    sum.update(0)
        .split(_1, _1, _1i, 32, TailStrategy::GuardWithIf)
        .split(_0, _0, _0i, 16, TailStrategy::GuardWithIf)
        .vectorize(_0i)
        .reorder({_0i, r99_x, _0, _1i, _1, _2})
        .parallel(_1);
    sliced
        .split(_0, _0, _0i, 16, TailStrategy::ShiftInwards)
        .vectorize(_0i)
        .compute_at(sum, _1)
        .reorder({_0i, _0, _1, _2});
    all_r
        .split(_0, _0, _0i, 16, TailStrategy::RoundUp)
        .vectorize(_0i)
        .compute_at(sum, _1)
        .reorder({_0i, _0, _1, _2});
    all_r.update(0)
        .split(_0, _0, _0i, 16, TailStrategy::GuardWithIf)
        .vectorize(_0i)
        .reorder({_0i, r85_x, _0, _1, _2});

}

#endif  // random_pipeline_SCHEDULE_H
